SELECT * FROM notas;
SELECT * FROM itens_notas;
SELECT * FROM tab_faturamento;

UPDATE itens_notas SET QUANTIDADE = 400
WHERE NUMERO = 107;

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_UPDATE AFTER UPDATE ON ITENS_NOTAS
FOR EACH ROW 
BEGIN
	DELETE FROM TAB_FATURAMENTO;
	INSERT INTO TAB_FATURAMENTO(
	SELECT N.DATA, SUM(QUANTIDADE * PRECO) AS TOTAL_FATURAMENTO
	FROM NOTAS N 
	INNER JOIN ITENS_NOTAS ITN
	ON N.NUMERO = ITN.NUMERO);
END//

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_DELETE AFTER DELETE ON ITENS_NOTAS
FOR EACH ROW 
BEGIN
	DELETE FROM TAB_FATURAMENTO;
	INSERT INTO TAB_FATURAMENTO(
	SELECT N.DATA, SUM(QUANTIDADE * PRECO) AS TOTAL_FATURAMENTO
	FROM NOTAS N 
	INNER JOIN ITENS_NOTAS ITN
	ON N.NUMERO = ITN.NUMERO);
END//

SELECT * FROM tab_faturamento;
SELECT * FROM notas;
SELECT * FROM ITENS_NOTAS;

INSERT INTO NOTAS(NUMERO, DATA, CPF, MATRICULA, IMPOSTO)
VALUES ('0107', '2019-05-08', '1471156710', '235', 0.10);
INSERT INTO ITENS_NOTAS(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0107', '1000889', 100, 10), ('0107', '1002334', 100, 10);

