USE VENDAS_SUCOS;

/*Inserindo dados na tabela*/
INSERT INTO PRODUTOS
	(CODIGO,DESCRITOR,
    SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040107', 'Light - 350ml - Melância', 'Melância', '350 ml', 'Lata', 4.56);

INSERT INTO PRODUTOS
	(CODIGO,DESCRITOR,
    SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040108', 'Light - 350ml - Graviola', 'Graviola', '350 ml', 'Lata', 4.00);

INSERT INTO PRODUTOS
VALUES ('1040109', 'Light - 350ml - Açai', 'Açai', '350 ml', 'Lata', 5.60);
-- Desta forma insere na posição de criação da tabela

INSERT INTO PRODUTOS
VALUES ('1040110', 'Light - 350ml - Jaca', 'Jaca', '350 ml', 'Lata', 6.00),
('1040111', 'Light - 350ml - Manga', 'Manga', '350 ml', 'Lata', 3.50);
-- Desta forma insere na posição de criação da tabela

SELECT * FROM PRODUTOS;

-- Exercicios
INSERT INTO clientes
(CPF,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA)
VALUES 
('1471156710','Érica Carvalho','R. Iriquitia','Jardins','São Paulo','SP','80012212','19900901',27,'F',170000,24500,0),
('19290992743','Fernando Cavalcante','R. Dois de Fevereiro','Água Santa','Rio de Janeiro','RJ','22000000','20000212',18,'M',100000,20000,1),
('2600586709','César Teixeira','Rua Conde de Bonfim','Tijuca','Rio de Janeiro','RJ','22020001','20000312',18,'M',120000,22000,0);

SELECT * FROM PRODUTOS;

/*INSERINDO MULTIPLOS REGISTROS*/
USE vendas_sucos;

SELECT * FROM sucos_vendas.tabela_de_produtos;

SELECT 
	CODIGO_DO_PRODUTO AS CODIGO,
    NOME_DO_PRODUTO AS DESCRITOR,
    SABOR,
    TAMANHO,
    EMBALAGEM, 
    PRECO_DE_LISTA AS PRECO_LISTA    
FROM sucos_vendas.tabela_de_produtos
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM produtos);

INSERT INTO produtos
SELECT 
	CODIGO_DO_PRODUTO AS CODIGO,
    NOME_DO_PRODUTO AS DESCRITOR,
    SABOR,
    TAMANHO,
    EMBALAGEM, 
    PRECO_DE_LISTA AS PRECO_LISTA    
FROM sucos_vendas.tabela_de_produtos
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM produtos);

SELECT * FROM PRODUTOS;

INSERT INTO clientes
(CPF,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA)

SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP,DATA_DE_NASCIMENTO AS  DATA_NASCIMENTO, IDADE, SEXO,LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA,PRIMEIRA_COMPRA 
 FROM sucos_vendas.tabela_de_clientes 
 WHERE CPF NOT IN (SELECT CPF FROM clientes);
 
 SELECT * FROM clientes;
 
 SELECT * FROM vendedores;