wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1661881267.226759
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.7.13
      5: 0.13.2
      8:
      - 3
      - 5
      10:
      - 9
